faume_salesforce:
  client:
    shortcode: '%env(FAUME_SALESFORCE_CLIENT_SHORTCODE)%'
    organization_id: '%env(FAUME_SALESFORCE_CLIENT_ORGANIZATION_ID)%'
    site_id: '%env(FAUME_SALESFORCE_CLIENT_SITE_ID)%'
    auth_domain: '%env(FAUME_SALESFORCE_CLIENT_AUTH_DOMAIN)%'
  discount_code:
    discount_code_end_at: '%env(FAUME_SALESFORCE_DISCOUNT_CODE_END_AT)%'
    multiple_codes_per_basket: '%env(FAUME_SALESFORCE_DISCOUNT_CODE_MULTIPLE_CODE_PER_BASKET)%'
    prefix: '%env(FAUME_SALESFORCE_DISCOUNT_CODE_PREFIX)%'
    description: '%env(FAUME_SALESFORCE_DISCOUNT_CODE_DESCRIPTION)%'
  campaign:
    prefix: '%env(FAUME_SALESFORCE_CAMPAIGN_PREFIX)%'
    description: '%env(FAUME_SALESFORCE_CAMPAIGN_DESCRIPTION)%'
  promotion:
    prefix: '%env(FAUME_SALESFORCE_PROMOTION_PREFIX)%'