faume_shopify:
    shopify_api_key: '%env(SHOPIFY_API_KEY)%'
    shopify_api_secret: '%env(SHOPIFY_API_SECRET)%'
    shopify_url: '%env(SHOPIFY_API_URL)%'
    shopify_access_token: '%env(SHOPIFY_ACCESS_TOKEN)%'
    discount_code_shopify_key: '%env(SHOPIFY_API_KEY)%'
    discount_code_shopify_secret: '%env(SHOPIFY_API_SECRET)%'
    discount_code_shopify_url: '%env(SHOPIFY_API_URL)%'
